
//Alice->Lido Finance: Sends ETH
//Lido Finance->Ethereum Network: Stakes Alice's ETH
//Ethereum Network-->Alice: Receives stETH
//Alice->Lido Finance: Transfers, trades, or lends stETH


// בוב הפקיד אצל אווהDAI
Bob->Aave: Deposits DAI
//אצל אווה הDAI של בוב הופקד
Aave->Aave: Bob's DAI deposited
//צארלס לווה מאווה USDC, מציע DAI כבטחון
Charles->Aave: Borrows USDC, offers DAI as collateral
//Aave->Aave: צ'ארלס לווה USDC
Aave->Aave: Charles borrows USDC
//Bob->Aave: מרוויח ריבית על DAI
Bob->Aave: Earns interest on DAI
//Charles->Aave: משלם ריבית על USDC
Charles->Aave: Pays interest on USDC

//דיאנה רוצה להחליף את ETH ב-LINK.
Diana->Uniswap: Provides ETH to liquidity pool
//דיאנה מקיימת אינטראקציה עם Uniswap, ומספקת ETH למאגר נזילות המכיל ETH ו-LINK.
Uniswap->Blockchain: Executes swap transaction on the blockchain
//המאגר מחליף אוטומטית את ה-ETH של דיאנה ל-LINK על סמך יחס המאגר הנוכחי.
Blockchain-->Uniswap: Confirms transaction
//דיאנה מקבלת LINK, 
Uniswap-->Diana: Sends LINK to Diana's wallet

Arik ->Ren Protocol: Locks BTC on Bitcoin network
Ren Protocol->Bitcoin Network: Locks BTC
Bitcoin Network-->Ren Protocol: Confirms locking
Ren Protocol->Ethereum Network: Mints renBTC
Ethereum Network-->Ren Protocol: Confirms minting
Ren Protocol-->Eric: Provides renBTC
