
coding:  {
  plugins: {
    gpt: {
      link: https://www.youtube.com/watch?v=7k0KZsheLP4
    }
  }

  editors: {
    neovim: {
      link: https://neovim.io/
    }
    vscode: {
      link: https://code.visualstudio.com/
    }
  }

  compilers: {
    foundry: {
      link: https://book.getfoundry.sh/
    }
  }
}

tokenomics: {
  hub: {
    link: https://design.tokenomicshub.xyz/
  }
}

composability:  {


a: |txt
  permissionles interoperability
  of DeFi protocols
 |


  aave: {
    link: https://aave.com/
  }
  maker-dao: {
    link: https://makerdao.com
  }
}

game-theory: {
}

languages: {
  solidity: {
    link: https://soliditylang.org/
  }
}

blockchain -> analytics
blockchain -> formal-verification
blockchain -> EVM
blockchain -> languages
blockchain -> game-theory
blockchain -> tokenomics
blockchain -> coding
blockchain -> wallets
blockchain -> cdbc
blockchain -> bridges
blockchain -> composability

languages.solidity -> audit

